name: Deploy automático na VPS (push para diogo)

on:
  push:
    branches:
      - diogo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Deploy via SSH na VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/erp-backend
            git pull origin diogo
            docker-compose down
            docker-compose up -d --build
