name: Deploy HML via SCP + Compose

on:
  push:
    branches: [main1]  # ou ajuste para a branch desejada

jobs:
  deploy:
    name: Deploy to HML VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Copiar projeto para a VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ./*
          target: /srv/erp/hml/

      - name: Executar docker-compose na VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "📦 Acessando diretório HML"
            cd /srv/erp/hml

            echo "🛑 Parando e removendo containers com nome contendo 'hml'..."
            docker ps -a --filter "name=hml" -q | xargs -r docker stop
            docker ps -a --filter "name=hml" -q | xargs -r docker rm

            echo "🧹 Executando docker compose down para limpar órfãos..."
            docker compose down --remove-orphans

            echo "🚀 Subindo nova versão da aplicação com build..."
            docker compose up -d --build
